import tailwindcss from '@tailwindcss/vite';
import { sveltekit } from '@sveltejs/kit/vite';
import * as fflate from 'fflate';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

import { defineConfig, searchForWorkspaceRoot } from 'vite';
import devtoolsJson from 'vite-plugin-devtools-json';

const __dirname = dirname(fileURLToPath(import.meta.url));

const GUIDE_FOR_FRONTEND = `
<!--
  This is a single file build of the GarClaw frontend.
  It is automatically generated by the build process.
  Do not edit this file directly.
-->
`.trim();

const MAX_BUNDLE_SIZE = 3 * 1024 * 1024;

/**
 * the maximum size of an embedded asset in bytes,
 * e.g. maximum size of embedded font (see node_modules/katex/dist/fonts/*.woff2)
 */
const MAX_ASSET_SIZE = 32000;

/** public/index.html.gz minified flag */
const ENABLE_JS_MINIFICATION = true;

function garclawBuildPlugin() {
        return {
                name: 'garclaw:build',
                apply: 'build' as const,
                closeBundle() {
                        // Ensure the SvelteKit adapter has finished writing to ../embed
                        setTimeout(() => {
                                try {
                                        const indexPath = resolve('../embed/index.html');

                                        if (!existsSync(indexPath)) {
                                                return;
                                        }

                                        let content = readFileSync(indexPath, 'utf-8');

                                        const faviconPath = resolve('static/favicon.svg');
                                        if (existsSync(faviconPath)) {
                                                const faviconContent = readFileSync(faviconPath, 'utf-8');
                                                const faviconBase64 = Buffer.from(faviconContent).toString('base64');
                                                const faviconDataUrl = `data:image/svg+xml;base64,${faviconBase64}`;

                                                content = content.replace(/href="[^"]*favicon\.svg"/g, `href="${faviconDataUrl}"`);

                                                console.log('✓ Inlined favicon.svg as base64 data URL');
                                        }

                                        content = content.replace(/\r/g, '');
                                        content = GUIDE_FOR_FRONTEND + '\n' + content;

                                        // For garclaw, we keep the uncompressed HTML for Go embed
                                        writeFileSync(indexPath, content);
                                        console.log('✓ Updated index.html');

                                        // Also create a gzipped version
                                        const compressed = fflate.gzipSync(Buffer.from(content, 'utf-8'), { level: 9 });

                                        if (compressed.byteLength > MAX_BUNDLE_SIZE) {
                                                throw new Error(
                                                        `Bundle size is too large (${Math.ceil(compressed.byteLength / 1024)} KB).\n` +
                                                                `Please reduce the size of the frontend or increase MAX_BUNDLE_SIZE in vite.config.ts.\n`
                                                );
                                        }

                                        writeFileSync(resolve('../embed/index.html.gz'), compressed);
                                        console.log('✓ Created index.html.gz');
                                } catch (error) {
                                        console.error('Failed to process build output:', error);
                                }
                        }, 100);
                }
        };
}

export default defineConfig({
        resolve: {
                alias: {
                        'katex-fonts': resolve('node_modules/katex/dist/fonts')
                }
        },
        build: {
                assetsInlineLimit: MAX_ASSET_SIZE,
                chunkSizeWarningLimit: 5000,
                minify: ENABLE_JS_MINIFICATION
        },
        css: {
                preprocessorOptions: {
                        scss: {
                                additionalData: `
                                        $use-woff2: true;
                                        $use-woff: false;
                                        $use-ttf: false;
                                `
                        }
                }
        },
        plugins: [tailwindcss(), sveltekit(), devtoolsJson(), garclawBuildPlugin()],

        server: {
                proxy: {
                        '/ws': {
                                target: 'ws://localhost:8080',
                                ws: true
                        }
                },
                headers: {
                        'Cross-Origin-Embedder-Policy': 'require-corp',
                        'Cross-Origin-Opener-Policy': 'same-origin'
                },
                fs: {
                        allow: [searchForWorkspaceRoot(process.cwd()), resolve(__dirname, 'tests')]
                }
        }
});
